name: CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install numpy
      run: |
        apk add --no-cache python3-dev libstdc++
        apk add --no-cache g++
        ln -s /usr/include/locale.h /usr/include/xlocale.h
        pip3 install numpy
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
      with:
        args: pip install cython>=0.29 && pip install numpy && pip install -r requirements.txt && pylint --rcfile=.pylintrc qbo_db_connector
        
