name: Pylint Check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Python Pylin GitHub Action
      uses: fylein/python-pylint-github-action@v4
      with:
        args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc qbo_db_connector
        
